### ISSUE TITLE
IA radio issues

### ISSUE THREAD

**Issue by Corsaka** [DDMers/Deep-Space-13#112]
## Round ID:
440

## Testmerges:
Server revision compiled on: 
Master commit: fabb9670635ff887731aa7089cb5b1dec5887f2f
The following pull requests are currently test merged:
#104: 'Columbia Escort Frigate' by Vasily2013 at commit e14f56d906
#111: 'Fixes some weird runabout behaviour' by Kmc2000 at commit e3f21bbb35

## Reproduction:
Step 1: play IA; Step 2: observe radio, and how it only has supply, command, and service channels.
![image](https://user-images.githubusercontent.com/23699128/59151133-c41a6d00-8a25-11e9-884c-9044963c92d8.png)

**Comment by alexkar598** [comment]
IA?

**Comment by Corsaka** [comment]
Internal Affairs, new in this update.

**Comment by alexkar598** [comment]
Working as intended:tm:

**Comment by SergeiKoralev** [comment]
IAA, at least in other servers, gets common and sec. Not sure how KMC wants to fully handle this, but I'll defer it to him.
