### ISSUE TITLE
Med staff don't have access to sleeper room/chem lab

### ISSUE THREAD

**Issue by ghost** [DDMers/Deep-Space-13#16]
## Testmerges:

Round ID: 26
BYOND Version: 512.1460
Server revision compiled on: 
Master commit: 37104ad460ffeb3a92c95e54e3e6140b3aac2562
The following pull requests are currently test merged:
#10: '(tested) Re-adds re-adding EMHs' by Kmc2000 at commit 9fb7407d70

Local commit: 6c9f4f9149e1b8bcc7282caf9f89f4945d46ee4c
Server tools version: 4.0.1.4

## Reproduction:

1. Attempt to enter the sleeper room via the doors as MD/CMO
2. fail to gain entry

it also seems chemists won't be able to open/leave their lab

to note, the airlocks are labeled as 'research wing'.

**Comment by Kmc2000** [comment]
https://github.com/DDMers/Deep-Space-13/pull/17
