### ISSUE TITLE
Staff Report 02/02/2019

### ISSUE THREAD

**Issue by WorldofLoina** [DDMers/Deep-Space-13#20]
- Door to chemistry is a research door not a medical door.
- You can only enter the translocater from the bottom left of the sprite
- Server seperates into two instances even on low population 
- Slimes spawn dead in Xeno
- Still able to spawn as AI with the AI preference off
- Arrival timings need to match crew pop / security pop
- Borg Adaptation is too slow with few Borg.

**Comment by Jalleo** [comment]
These issues are known. Instances issue we need to talk to Cyberboss about it.
