### ISSUE TITLE
Shaft Miner PDA sprites

### ISSUE THREAD

**Issue by ghost** [DDMers/Deep-Space-13#28]
## Testmerges:

Round ID: 93
BYOND Version: 512.1453
Server revision compiled on: 
Master commit: b58ec82b3aa324850a2e9135cc67f0a53ab5f619
The following pull requests are currently test merged:
#27: 'Resprites some common tools+items, fixes medbay doors' by Kmc2000 at commit 33765afb62

Local commit: d021776b20f91c7c805acdd374c8ec32014f7678
Server tools version: 4.0.1.4

## Reproduction:

The sprite for the shaft miner's PDA is broken, it's only a grey line.

**Comment by Kmc2000** [comment]
Can you remember where your PDA spawned? Left pocket, Right pocket, or Belt?
