### ISSUE TITLE
Medical Bay is not on the turbolift menu

### ISSUE THREAD

**Issue by WorldofLoina** [DDMers/Deep-Space-13#48]
## Reproduction:
Go to turbolift, look at turbolift menu, be confused as to where Medical Bay is

**Comment by soryy708** [comment]
Should be deck 2 aye?

**Comment by WorldofLoina** [comment]
Yep

**Comment by soryy708** [comment]
Is it called "medical bay" or "sick bay"?

**Comment by Kmc2000** [comment]
Resolved
