### ISSUE TITLE
Mapping Check Megathread

### ISSUE THREAD

**Issue by francinum** [DDMers/Deep-Space-13#51]
```
Mixed Air Supply Control at Atmospherics (128, 146, 2):

Failed to find a valid outlet injector as an input with the tag air_in.
Failed to find a valid siphon pump as an outlet with the tag air_out.
```
Unconnected air supply pipe located at Command Hallway (112, 143, 4) (JMP)
Unconnected air supply pipe located at Command Hallway (116, 143, 4) (JMP)
https://i.imgur.com/SHO0yDY.png

Unconnected air supply pipe located at Engineering Maintenance (99, 148, 2) (JMP)
Unconnected air supply pipe located at Engineering Maintenance (101, 148, 2) (JMP)
https://i.imgur.com/il1KqC0.png

Unconnected scrubbers pipe located at Engineering (106, 125, 2) (JMP)
https://i.imgur.com/icRlrWy.png

Unconnected air supply pipe located at Engineering (113, 111, 2) (JMP)
https://i.imgur.com/xcXFMG1.png

Unconnected scrubbers pipe located at Engineering (122, 125, 2) (JMP)
https://i.imgur.com/2VqrcYL.png

Unconnected pipe located at Atmospherics (137, 147, 2) (JMP)
https://i.imgur.com/gr6azcu.png

Unconnected scrubbers pipe located at Brig (84, 145, 3) (JMP)
https://i.imgur.com/TsjeP9d.png `THIS EQUIPMENT IS ALSO STACKED. SPLIT THEM, THIS IS AN INVALID STATE`

Unconnected air supply pipe located at Bridge (112, 145, 4) (JMP)
Unconnected air supply pipe located at Bridge (116, 145, 4) (JMP)
https://i.imgur.com/SHO0yDY.png

Shipside AT: https://i.imgur.com/yCvdp2C.png

The Unimatrix Wreck has too many to list.
The Comet has even more.
Same with the Retro.

**Comment by Kmc2000** [comment]
He's speaking the language of the gods
