### ISSUE TITLE
move-upwards and move-down verbs don't work

### ISSUE THREAD

**Issue by soryy708** [DDMers/Deep-Space-13#53]
## Reproduction:

1. Join as AI
2. type `move-upwards`
3. Fail miserably
4. type `move-down`
5. Fail too

**Comment by Kmc2000** [comment]
You need to use the buttons, there isn't a move down or up verb (check the arrows next to your camera)

**Comment by soryy708** [comment]
The buttons work.
The verb exists, but using it says there's no z-level above/below.

**Comment by Kmc2000** [comment]
Whack

**Comment by soryy708** [comment]
What?
