### ISSUE TITLE
AI chamber should be accessible on Akira

### ISSUE THREAD

**Issue by WorldofLoina** [DDMers/Deep-Space-13#58]
(Currently writing this as I watch KMC try to extract the AI from a sealed room)

the AI is already in the bridge and behind two doors, yet it is physically inaccessible for antag high jinks.

It uh.. It should be, that's my suggestion.

**Comment by soryy708** [comment]
Last time there were antags, it was a meme round. From what I've gathered so far, the experience on this server is different from standard ss13. There's plenty of tension generated by the scripted quests given to the ship very often.
Whether the design should be friendly to antag game modes should be an executive-level decision of the staff here.

**Comment by Kmc2000** [comment]
This is mainly so the crew can evacuate their AI.
I'll make it so
