### ISSUE TITLE
Protection Suits stored outside the Warp Coils don't protect against the Warp Coils

### ISSUE THREAD

**Issue by WorldofLoina** [DDMers/Deep-Space-13#59]
## Reproduction:
The suits stored outside of the warp coils, (resprited to the Star Trek EVA suits) aren't enough to protect you if you need to go into the warp coils as you begin to die from radiation.

**Comment by Kmc2000** [comment]
This is intentional. They give you 90% protection from coils but they are literally distorting the space around you.
Your best option is to starve them of plasma / turn off the APC's equipment channel first, so they shut off.
