### ISSUE TITLE
Uniform Jackets

### ISSUE THREAD

**Issue by ghost** [DDMers/Deep-Space-13#6]
## Round ID:

Round ID: 10
BYOND Version: 512.1460
Server revision compiled on: 
Master commit: 9f197fae2b406b1e49c64251ec12247d1c34c6cc
The following pull requests are currently test merged:
#5: 'Adds emergency medical holograms!' by Kmc2000 at commit cc63d13ff3

Local commit: c79c944f5fafce3f038a3c98e0a3c59ad60a8852
Server tools version: 4.0.1.4

## Reproduction:

Two issues, the first:
Uniform Jackets claim to have 5 pockets, but one pocket is taken up by the jacket iself when worn on a jumpsuit. The jacket does keep all 5 pockets when not on a jumpsuit, but seems to have it's own inventory separately. IE, a uniform jacket on a jumpsuit will always have the first slot taken up by the jacket, with 4 to spare.
Accessing the jacket when it's not attached to a jumpsuit allows all 5 slots to be filled.
However, the jacket seems to have a separate inventory when on and off a jumpsuit. In theory, this can be used for 9 pockets.

Issue two:
Trying to put a jumpsuit on with a uniform jacket attached simply picks up the jacket and not the jumpsuit. The jumpsuit can be worn after removing the jacket from it.

**Comment by Jalleo** [comment]
@Kmc2000

**Comment by Kmc2000** [comment]
Fixed some of this issue but not the storage thing. Need to remember to do that
