### ISSUE TITLE
Estimate effort required for merging from upstream

### ISSUE THREAD

**Issue by soryy708** [DDMers/Deep-Space-13#65]
This repository is a fork of [tgstation](https://github.com/tgstation/tgstation).
It was forked from [commit #57c6448](https://github.com/tgstation/tgstation/commit/57c64485b817fad6afc3e452fd2f51d33381d7fd) ([tgstation state](https://github.com/tgstation/tgstation/tree/57c64485b817fad6afc3e452fd2f51d33381d7fd) at the time of the fork).
It happened on 7th January.

It's been over 4 months since the fork. On 7th January, tgstation had 61585 commits. As of writing, it has 62999 commits. That is 1414 commits difference.

The sheer volume of the divergence is expected to make merging from upstream difficult. Estimate effort required to merge from upstream, and map out the kind of bugs that may occur due to merge.

**Comment by Kmc2000** [comment]
Not too hard, no.
But tg's done some questionable things since then.

**Comment by soryy708** [comment]
> Not too hard, no.

Can this be quantified?

> tg's done some questionable things since then

If so, do you still need the option to merge from them?

**Comment by Kmc2000** [comment]
We will eventually be forced to rebase for performance gains, admin tools and such. 

I cannot quantify the effort required, but our changes are modular + commented

**Comment by soryy708** [comment]
Not all.
