### ISSUE TITLE
Staff Report 19/01/2019

### ISSUE THREAD

**Issue by MrSeaside** [DDMers/Deep-Space-13#7]
o EMH Bugs:
- It can be killed
- It can be summoned against its will
- Admin ghosting as the EMH will ask ghosts if they want to be the EMH

o Airlocks not transparent
o Comms on all decks
o Access is inconsistent for every job
o No QM access to cargonia
o Both buttons on the wall in chem do the same thing
o Hull should be named tritanium
o every wall in the map is on ssfastprocess or something
o exponential CPU leak
o greytide mcgee and the traitor three can access the SM without effort due to mapping of ladders.
o **STATION HAS NO SIGNPOSTING**
o Remove SM ladders
o Add an extra layer of vertical airlocks for escape
o **ADD ATMOS**

**Comment by Jalleo** [comment]
These are all reported from players and just pasted here.

**Comment by WorldofLoina** [comment]
To explain "It can be summoned against its will"
It asks the person summoning the EMH if they want to be summoned when its written like it should be asking the EMH

**Comment by Jalleo** [comment]
Ah yeah I understand what can cause that.
